### PR TITLE
Fix warnings about replacing original key "FILES_kernel-image"

### PR DESCRIPTION
**Pull request by persianpros**
Fix warnings about replacing original key "FILES_kernel-image"
* Update linux-vuplus-4.1.45.inc
* Update linux-vuplus-4.1.20.inc
* Update linux-vuplus-3.9.6.inc
* Update linux-vuplus-3.14.28.inc
* Update linux-vuplus-3.13.5.inc

### CODE REVIEW

**Comment by persianpros** [comment]
Would you please merge this? We get error each time just because of your meta.

**Comment by vu-plus** [comment]
Hello, persianpros.

I am sorry to be unable to merge your request because of a kernel build error in oecore-sumo.

If you give me a detailed description of your OE build environment and build error messages, I'll try to build it and find a solution.

Thanks.

**Comment by persianpros** [comment]
Hi vu-plus,

Just use PLi's develop OE and you'll see, @WanWizard don't you see this errors as well my friend?

Regards,
Persian Prince

**Comment by vu-plus** [comment]
Could you tell me name of branch on PLi's develop OE?

Thanks.

**Comment by persianpros** [comment]
"develop" branch.

**Comment by WanWizard** [comment]
off course we do:
````
Parsing recipes...WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuzero_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuzero4k_4.1.20.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuuno_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuuno4kse_4.1.20.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuuno4k_3.14.28.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuultimo_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuultimo4k_3.14.28.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vusolo_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vusolose_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vusolo4k_3.14.28.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vusolo2_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuduo4k_4.1.45.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuduo_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /openpli/oe/develop/meta-vuplus/recipes-bsp/linux/linux-vuduo2_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
done.
````

**Comment by vu-plus** [comment]
Hi, persianpros

I have applied your request.

But, sumo issue (https://github.com/vu-plus/meta-vuplus/pull/55) seems to be reopened later.

I have not yet found a way to solve both.

But, I'll update it back to the correct one.

Thank you.

**Pull request closed without merging**
