### PR TITLE
Add kernel modules for Panasonic mn8847x

### PR DESCRIPTION
**Pull request by AbuBaniaz**
The driver is available at mainline Linux since Kernel 4.16-rc1
https://www.linuxtv.org/wiki/index.php/Xbox_One_Digital_TV_Tuner

These are typically in Xbox One and Transmeta DVB-T2 USB tuners

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Please see PLI threads here

https://forums.openpli.org/topic/67209-mn8847x-support/
https://forums.openpli.org/topic/75914-xbox-usb-tuner/

**Comment by eriksl** [comment]
VU+ developers, please apply.

**Comment by vu-plus** [comment]
I have applied now.
Thank you.

**Comment by AbuBaniaz** [comment]
Thanks.

**Comment by eriksl** [comment]
Thanks VU+

**Pull request closed without merging**
